name: Deploy Website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_site: # Matches the job name in your screenshots
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4.1.7
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      # actions/setup-node@v4.0.3
      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # actions/upload-pages-artifact@v3.0.1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56461b9ad0d4c0b48da937d7703d9697996df6bd
        with:
          # Ensure this matches your build folder (usually 'dist' or 'build')
          path: './dist'

      # actions/deploy-pages@v4.0.5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db9015773b9687e124b278f93495d012fe72ee
